### ISSUE TITLE
脚本在tis网站无法被执行的问题

### ISSUE THREAD

**Issue by wyh1309** [Vollate/SUSTech-its-helper#1]
您好，我的脚本在tis网站上显示它无法被执行，具体问题如图所示。希望作者能帮忙解决一下，谢谢！
![下载](https://github.com/user-attachments/assets/2f1142dc-1e19-4732-b14b-53d05dd42e4a)

**Comment by vollate** [comment]
你没有开启浏览器插件的开发者模式，[参考这个开启](https://www.tampermonkey.net/faq.php?locale=en#:~:text=Open%20the%20menu%2C%20select%20%22Extensions,navigate%20to%20the%20extensions%20page.&text=Find%20and%20click%20the%20%22Developer,top%20right%20to%20enable%20it.)

**Comment by wyh1309** [comment]
问题已解决。谢谢作者！

**Comment by wyh1309** [comment]
太谢谢您了！问题已解决。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月30日(周五) 上午8:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [vollate/SUSTech-tis-cheater] 脚本在tis网站无法被执行的问题 (Issue #1)




 
你没有开启浏览器插件的开发者模式，参考这个开启
